root_dir = "/Users/rwblickhan/Developer/astro-rwblickhan.org/main/dist"
exclude = [
  "https://app.thestorygraph.com",
  "https://worldcat.org",
  "https://search.worldcat.org",
]
include_fragments = "full"
index_files = ["index.html"]
