[tasks.dev]
alias = 'd'
run = 'pnpm run dev'

[tasks.build]
alias = 'b'
run = 'pnpm run build'

[tasks.check]
run = 'pnpm run astro check'

[tasks.clean]
run = 'rm -rf _dist/*'

[tasks.push]
alias = 'p'
run = 'fish -c "utils/push"'

[tasks.sync]
alias = 's'
run = 'pnpm run astro sync'

[tasks.lint]
alias = 'l'
run = "pnpm exec markdownlint 'src/**/*.md' 'src/**/*.mdx' && pnpm exec astro check"

[tasks.format]
alias = 'f'
run = 'pnpm exec prettier --write .'
