[tools]
hk = "latest"
lychee = "latest"
"npm:astro" = "latest"
"npm:wrangler" = "latest"
pkl = "latest"
pnpm = "latest"

[hooks]
postinstall = "hk install"

[tasks.dev]
alias = 'd'
run = 'pnpm run dev'

[tasks.build]
alias = 'b'
run = 'pnpm run build'

[tasks.clean]
run = 'rm -rf _dist/*'

[tasks.sync]
alias = 's'
run = 'pnpm run astro sync'

[tasks.lint]
alias = 'l'
run = 'hk check'

[tasks.format]
alias = 'f'
run = 'pnpm exec prettier --write .'
