name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Restore cached images
        id: cache-images-restore
        uses: actions/cache/restore@v4
        with:
          path: cache
          key: _astro
      - run: npm ci
      - run: npm run build
      - name: Build & Deploy Site
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.14.4"
      - name: Check if images cache exists for current branch
        id: actions-cache-list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "RESULT=$(gh actions-cache list --branch ${{ github.ref }} --key Images-)" >> $GITHUB_OUTPUT
      - name: Clear existing images cache
        if: ${{ steps.actions-cache-list.outputs.RESULT != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete ${{ steps.cache-images-restore.outputs.cache-primary-key }}
      - name: Cache images
        uses: actions/cache/save@v4
        with:
          path: cache
          key: ${{ steps.cache-images-restore.outputs.cache-primary-key }}
