name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i
      - name: Run markdownlint
        run: pnpm exec markdownlint 'src/**/*.md' 'src/**/*.mdx'
      - name: Run astro check
        run: pnpm exec astro check
